# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3
language: swift

before_install:
- gem install bundler
- bundle install
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3' -enableCodeCoverage YES -workspace Example/PromiseLite.xcworkspace -scheme PromiseLite_Tests ONLY_ACTIVE_ARCH=YES | xcpretty
- pod lib lint

after_success:
- bash <(curl -s https://codecov.io/bash)
